name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Echo the message
        run: |
          echo "Hello World"
        
